<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-8IL510P" failures="1" tests="1" name="Default test(failed)" time="4.27" errors="0" timestamp="2022-09-22T02:01:43 IST">
  <testcase classname="runOnlyFailedTestCases.RunFailTest" name="verifyUrlOfPage" time="0.009">
    <failure type="java.lang.AssertionError" message="Verify url of page expected [https://www.fkart.com/] but found [https://www.flipkart.com/]">
      <![CDATA[java.lang.AssertionError: Verify url of page expected [https://www.fkart.com/] but found [https://www.flipkart.com/]
at runOnlyFailedTestCases.RunFailTest.verifyUrlOfPage(RunFailTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyUrlOfPage -->
  <testcase classname="runOnlyFailedTestCases.RunFailTest" name="verifyPageTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyPageTitle -->
</testsuite> <!-- Default test(failed) -->
